version: 2
ethernets:
  ens3:
    dhcp4: false
    addresses:
      - 15.1.1.12/24  # Static IP untuk node-2
    gateway4: 15.1.1.1
    nameservers:
      addresses:
        - 8.8.8.8
        - 8.8.4.4

