executor: KubernetesExecutor
createUserJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  useHelmHooks: false
  applyCustomEnv: false
migrateDatabaseJob:
  jobAnnotations:
    "argocd.argoproj.io/hook": Sync

postgresql:
  persistence:
    enabled: true
    size: 8Gi  # Ukuran disk untuk PostgreSQL
    storageClassName: nfs  # StorageClass yang digunakan (ganti dengan sesuai kebutuhan)

redis:
  persistence:
    enabled: true
    size: 1Gi  # Ukuran disk untuk Redis
    storageClassName: nfs  # StorageClass untuk Redis (ganti dengan sesuai kebutuhan)

workers:
  persistence:
    enabled: true
    size: 5Gi  # Ukuran disk untuk logs
    storageClassName: nfs  # Ganti dengan StorageClass yang sesuai
    accessMode: ReadWriteMany

